name: Build Docker image

on:
  push:

jobs:
  prepare:
    name: Prepare build variables
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.vars.outputs.image }}
      branch: ${{ steps.vars.outputs.branch }}
      commit: ${{ steps.vars.outputs.commit }}
    steps:
      - name: Generate tags and commit SHA
        id: vars
        run: |
          echo "image=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "branch=$(echo "${{ github.ref_name }}" | sed 's#/#-#g')" >> $GITHUB_OUTPUT
          echo "commit=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

  build:
    name: Build for ${{ matrix.arch }}
    needs: prepare
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            arch: arm64
            runner: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push arch-specific image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          push: true
          provenance: false
          tags: ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.commit }}-${{ matrix.arch }}

  push_manifest:
    name: Push multi-arch manifest
    needs: [prepare, build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest list
        run: |
          docker manifest create ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.branch }} \
            --amend ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.commit }}-amd64 \
            --amend ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.commit }}-arm64
          
          docker manifest create ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.commit }} \
            --amend ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.commit }}-amd64 \
            --amend ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.commit }}-arm64

          docker manifest push ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.branch }}
          docker manifest push ${{ needs.prepare.outputs.image }}:${{ needs.prepare.outputs.commit }}
